name: build

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.19.x, 20.11.x, 22.x]

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
    - name: install package
      run: |
        npm install -g @angular/cli@19
        npm ci
    - name: run tests
      run: |
        ./run-tests.sh

      env:
        CI: true
